# Site settings
title: המאור לבית - חשמל ותחזוקה
description: שירותי חשמל ותחזוקה מקצועיים
baseurl: ""
url: ""

# Build settings
theme: jekyll-theme-primer
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Directory settings
source: .
destination: ./_site
